FROM gcr.io/coinos-326717/github.com/tokenocean/raretoshi:base

ENV NODE_ENV staging

WORKDIR /app
COPY . .
RUN sed -i '/cypress/d' package.json
RUN sed -i 's/bid.nftglee.com/nftglee.tokenocean.io/g' .env.production
RUN mv /deps/node_modules /app
RUN pnpm build

CMD ["node", "build"]
